name: "Bump Version"

on:
  push:
    tags:
      - '*'

jobs:
  bump-version:
    name: "Bump Version on package.json"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
             
      - name: Update version in package.json
        run: echo "$(git tag --points-at HEAD)"
             npm version --no-git-tag-version (git tag --points-at HEAD)

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Updated version in package.json
