name: "Bump Version"

on:
  push:
    tags:
      - '*'

jobs:
  bump-version:
    name: "Bump Version on package.json"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
          
  
      - name: "Check if Git tag exists"
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
      - name: "Set git config"
        run: git config --local user.email "$(git log --format='%ae' HEAD^!)"
             git config --local user.name "$(git log --format='%an' HEAD^!)"
      - name: Update version in package.json
        run: npm version env.HEAD_TAG

