name: "Bump Version"

on:
  push:
    tags:
      - '*'

jobs:
  bump-version:
    name: "Bump Version on package.json"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
           
      - name: Tag
        run: echo "RELEASE_VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV
           
      - name: Update version in package.json
        run: npm version --no-git-tag-version "${{ env.RELEASE_VERSION }}"

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: master
          commit_message: Updated version in package.json
